spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/apperadb
    password: ${MYSQL_ROOT_PASSWORD}
    username: ${MYSQL_ROOT_USER}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      hibernate.format_sql: true
server:
  port: 9000

secret:
  key: 8HHUNJRR848HON48848